# permissions for end users to view hypernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypernode-viewer-role
rules:
- apiGroups:
  - cluster.pml.com.cn
  resources:
  - hypernodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.pml.com.cn
  resources:
  - hypernodes/status
  verbs:
  - get
