# permissions for end users to edit hypernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypernode-editor-role
rules:
- apiGroups:
  - cluster.pml.com.cn
  resources:
  - hypernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.pml.com.cn
  resources:
  - hypernodes/status
  verbs:
  - get
