// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: computedriver.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox []*SandboxInfo `protobuf:"bytes,1,rep,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *SandboxList) Reset() {
	*x = SandboxList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computedriver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxList) ProtoMessage() {}

func (x *SandboxList) ProtoReflect() protoreflect.Message {
	mi := &file_computedriver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxList.ProtoReflect.Descriptor instead.
func (*SandboxList) Descriptor() ([]byte, []int) {
	return file_computedriver_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxList) GetSandbox() []*SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type SandboxInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//sandbox name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// sandbox version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// sandbox url.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// sandbox type.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computedriver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_computedriver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_computedriver_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SandboxInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SandboxInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SandboxReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//return code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//return message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SandboxReply) Reset() {
	*x = SandboxReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computedriver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxReply) ProtoMessage() {}

func (x *SandboxReply) ProtoReflect() protoreflect.Message {
	mi := &file_computedriver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxReply.ProtoReflect.Descriptor instead.
func (*SandboxReply) Descriptor() ([]byte, []int) {
	return file_computedriver_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SandboxReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_computedriver_proto protoreflect.FileDescriptor

var file_computedriver_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x22, 0x3c, 0x0a,
	0x0b, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x22, 0x61, 0x0a, 0x0b, 0x53,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3c,
	0x0a, 0x0c, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x47, 0x0a, 0x0a,
	0x52, 0x75, 0x6e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x39, 0x0a, 0x0a, 0x72, 0x75,
	0x6e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x13, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_computedriver_proto_rawDescOnce sync.Once
	file_computedriver_proto_rawDescData = file_computedriver_proto_rawDesc
)

func file_computedriver_proto_rawDescGZIP() []byte {
	file_computedriver_proto_rawDescOnce.Do(func() {
		file_computedriver_proto_rawDescData = protoimpl.X.CompressGZIP(file_computedriver_proto_rawDescData)
	})
	return file_computedriver_proto_rawDescData
}

var file_computedriver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_computedriver_proto_goTypes = []interface{}{
	(*SandboxList)(nil),  // 0: driver.SandboxList
	(*SandboxInfo)(nil),  // 1: driver.SandboxInfo
	(*SandboxReply)(nil), // 2: driver.SandboxReply
}
var file_computedriver_proto_depIdxs = []int32{
	1, // 0: driver.SandboxList.sandbox:type_name -> driver.SandboxInfo
	0, // 1: driver.RunSandbox.runSandbox:input_type -> driver.SandboxList
	2, // 2: driver.RunSandbox.runSandbox:output_type -> driver.SandboxReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_computedriver_proto_init() }
func file_computedriver_proto_init() {
	if File_computedriver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_computedriver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computedriver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computedriver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_computedriver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_computedriver_proto_goTypes,
		DependencyIndexes: file_computedriver_proto_depIdxs,
		MessageInfos:      file_computedriver_proto_msgTypes,
	}.Build()
	File_computedriver_proto = out.File
	file_computedriver_proto_rawDesc = nil
	file_computedriver_proto_goTypes = nil
	file_computedriver_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RunSandboxClient is the client API for RunSandbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunSandboxClient interface {
	RunSandbox(ctx context.Context, in *SandboxList, opts ...grpc.CallOption) (*SandboxReply, error)
}

type runSandboxClient struct {
	cc grpc.ClientConnInterface
}

func NewRunSandboxClient(cc grpc.ClientConnInterface) RunSandboxClient {
	return &runSandboxClient{cc}
}

func (c *runSandboxClient) RunSandbox(ctx context.Context, in *SandboxList, opts ...grpc.CallOption) (*SandboxReply, error) {
	out := new(SandboxReply)
	err := c.cc.Invoke(ctx, "/driver.RunSandbox/runSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunSandboxServer is the server API for RunSandbox service.
type RunSandboxServer interface {
	RunSandbox(context.Context, *SandboxList) (*SandboxReply, error)
}

// UnimplementedRunSandboxServer can be embedded to have forward compatible implementations.
type UnimplementedRunSandboxServer struct {
}

func (*UnimplementedRunSandboxServer) RunSandbox(context.Context, *SandboxList) (*SandboxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSandbox not implemented")
}

func RegisterRunSandboxServer(s *grpc.Server, srv RunSandboxServer) {
	s.RegisterService(&_RunSandbox_serviceDesc, srv)
}

func _RunSandbox_RunSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunSandboxServer).RunSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/driver.RunSandbox/RunSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunSandboxServer).RunSandbox(ctx, req.(*SandboxList))
	}
	return interceptor(ctx, in, info, handler)
}

var _RunSandbox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "driver.RunSandbox",
	HandlerType: (*RunSandboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "runSandbox",
			Handler:    _RunSandbox_RunSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "computedriver.proto",
}
